- name: Mitigate CVE-2023-20198 Critical Vulnerability
  hosts: sandbox-iosxe-recomm-1.cisco.com
  gather_facts: false
  vars: 
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: developer
    ansible_password: lastorangerestoreball8876
    ansible_port: 22

  tasks:
  - name: Check if Web service is running on router
    cisco.ios.command:
      commands: show running-config | include ip http server|secure|active
    register: user_output

  - name: Print results
    ansible.builtin.debug:
      var: user_output.stdout_lines[0]

  - name: If needed, disable Web User Interface of Cisco IOS XE
    cisco.ios.ios_config:
      lines: 
      - no ip http server
      - no ip http secure-server
      save_when: changed
    when: user_output.stdout[0] != "no ip http server\nno ip http secure-server"
    
  - name: Determine if exploit exists in syslogs
    cisco.ios.command:
      commands: 
      - 'sh logging | i %SYS-5-CONFIG_P: Configured programmatically by process SEP_webui_wsma_http from console as'
      - 'sh logging | i %SEC_LOGIN-5-WEBLOGIN_SUCCESS: Login Success'
      - 'sh logging | i %WEBUI-6-INSTALL_OPERATION_INFO:''
    register: Logging_output

  - name: Print results
    ansible.builtin.debug:
     var: Logging_output.stdout_lines